# Generated by Django 5.2.1 on 2025-06-05 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "fecha_fallecimiento",
                    models.DateField(blank=True, null=True, verbose_name="Fallecido"),
                ),
                ("biografia", models.TextField(blank=True, max_length=1000)),
            ],
            options={
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ingrese el nombre del género", max_length=200
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "resumen",
                    models.TextField(
                        help_text="Ingrese una breve descripción del libro",
                        max_length=1000,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>',
                        max_length=13,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                ("idioma", models.CharField(default="Español", max_length=20)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio del libro",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libros",
                        to="catalogo.autor",
                    ),
                ),
                (
                    "genero",
                    models.ManyToManyField(
                        help_text="Seleccione un género para este libro",
                        to="catalogo.genero",
                    ),
                ),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="EjemplarLibro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="ID único para este ejemplar particular",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_adquisicion", models.DateField(blank=True, null=True)),
                ("fecha_devolucion", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Mantenimiento"),
                            ("p", "Prestado"),
                            ("d", "Disponible"),
                            ("r", "Reservado"),
                        ],
                        default="d",
                        help_text="Disponibilidad del libro",
                        max_length=1,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ejemplares",
                        to="catalogo.libro",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_devolucion"],
                "permissions": (
                    ("puede_marcar_devuelto", "Marcar libro como devuelto"),
                ),
            },
        ),
        migrations.AddIndex(
            model_name="libro",
            index=models.Index(fields=["titulo"], name="catalogo_li_titulo_767fc8_idx"),
        ),
        migrations.AddIndex(
            model_name="libro",
            index=models.Index(fields=["isbn"], name="catalogo_li_isbn_1fa761_idx"),
        ),
    ]
