# Generated by Django 5.2.1 on 2026-09-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Portada del libro', null=True, upload_to='libros/'),
        ),
    ]
